<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Capítulo 13 Las pruebas “Chi-cuadrado” | Fundamentos de Inferencia Estadistica</title>
<meta name="author" content="Alex Sanchez Pla y Santiago Pérez Hoyos">
<meta name="generator" content="bookdown 0.46 with bs4_book()">
<meta property="og:title" content="Capítulo 13 Las pruebas “Chi-cuadrado” | Fundamentos de Inferencia Estadistica">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Capítulo 13 Las pruebas “Chi-cuadrado” | Fundamentos de Inferencia Estadistica">
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.10.0/transition.js"></script><script src="libs/bs3compat-0.10.0/tabs.js"></script><script src="libs/bs3compat-0.10.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><style type="text/css">div.hanging-indent{margin-left:1.5em;text-indent:-1.5em;}</style>
<style type="text/css">div.csl-bib-body{}div.csl-entry{clear:both;margin-bottom:0em;}.hanging div.csl-entry{margin-left:2em;text-indent:-2em;}div.csl-left-margin{min-width:2em;float:left;}div.csl-right-inline{margin-left:2em;padding-left:1em;}div.csl-indent{margin-left:2em;}</style>
<link rel="stylesheet" href="blocks.css">
<link rel="stylesheet" href="bs4-style.css">
<meta name="description" content="Teoría (PDF)  Ejercicios (PDF)   13.1 Introducción Con el nombre de pruebas de chi-cuadrado se conoce una variedad de contrastes estadísticos que hacen referencia a problemas distintos pero que...">
<meta property="og:description" content="Teoría (PDF)  Ejercicios (PDF)   13.1 Introducción Con el nombre de pruebas de chi-cuadrado se conoce una variedad de contrastes estadísticos que hacen referencia a problemas distintos pero que...">
<meta name="twitter:description" content="Teoría (PDF)  Ejercicios (PDF)   13.1 Introducción Con el nombre de pruebas de chi-cuadrado se conoce una variedad de contrastes estadísticos que hacen referencia a problemas distintos pero que...">
</head>
<body data-spy="scroll" data-target="#toc">
<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>
    <div class="d-flex align-items-start justify-content-between">
      <h1><a href="index.html" title="">Fundamentos de Inferencia Estadistica</a></h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>
    <div id="main-nav" class="collapse-lg">
      <form role="search"><input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search"></form>
      <nav aria-label="Tabla de contenidos"><h2>Tabla de contenidos</h2>
<ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Presentación</a></li>
<li><a class="" href="agradecimiento-y-fuentes-utilizadas.html">Agradecimiento y fuentes utilizadas</a></li>
<li class="book-part">Teoría</li>
<li><a class="" href="probabilidad-y-experimentos-aleatorios.html"><span class="header-section-number">1</span> Probabilidad y Experimentos aleatorios</a></li>
<li><a class="" href="variables-aleatorias-y-distribuciones-de-probabilidad.html"><span class="header-section-number">2</span> Variables aleatorias y Distribuciones de probabilidad</a></li>
<li><a class="" href="distribuciones-notables.html"><span class="header-section-number">3</span> Distribuciones Notables</a></li>
<li><a class="" href="distribuciones-de-probabilidad-multidimensionales.html"><span class="header-section-number">4</span> Distribuciones de probabilidad multidimensionales</a></li>
<li><a class="" href="grandes-muestras.html"><span class="header-section-number">5</span> Grandes muestras</a></li>
<li><a class="" href="introducci%C3%B3n-a-la-inferencia-estad%C3%ADstica.html"><span class="header-section-number">6</span> Introducción a la inferencia estadística</a></li>
<li><a class="" href="estimaci%C3%B3n-puntual.html"><span class="header-section-number">7</span> Estimación puntual</a></li>
<li><a class="" href="estimaci%C3%B3n-por-int%C3%A9rvalos.html"><span class="header-section-number">8</span> Estimación por intérvalos</a></li>
<li><a class="" href="pruebas-de-hip%C3%B3tesis.html"><span class="header-section-number">9</span> Pruebas de hipótesis</a></li>
<li><a class="" href="construcci%C3%B3n-de-contrastes-de-hip%C3%B3tesis.html"><span class="header-section-number">10</span> Construcción de contrastes de hipótesis</a></li>
<li><a class="" href="pruebas-de-una-muestra.html"><span class="header-section-number">11</span> Pruebas de una muestra</a></li>
<li><a class="" href="contrastes-con-dos-muestras.html"><span class="header-section-number">12</span> Contrastes con dos muestras</a></li>
<li><a class="active" href="las-pruebas-chi-cuadrado.html"><span class="header-section-number">13</span> Las pruebas “Chi-cuadrado”</a></li>
<li><a class="" href="estad%C3%ADstica-no-param%C3%A9trica.html"><span class="header-section-number">14</span> Estadística no paramétrica</a></li>
<li><a class="" href="m%C3%A9todos-de-computaci%C3%B3n-intensiva-el-bootstrap.html"><span class="header-section-number">15</span> Métodos de computación intensiva: El Bootstrap</a></li>
<li class="book-part">Ejercicios</li>
<li><a class="" href="ex-presentacion.html">Presentación</a></li>
<li><a class="" href="ex-probabilidad.html"><span class="header-section-number">16</span> Probabilidad y Experimentos aleatorios</a></li>
<li><a class="" href="ex-variables-aleatorias.html"><span class="header-section-number">17</span> Variables aleatorias y Distribuciones de probabilidad</a></li>
<li><a class="" href="ex-distribuciones-multivariantes.html"><span class="header-section-number">18</span> Distribuciones de probabilidad multidimensionales</a></li>
<li><a class="" href="ex-muestreo.html"><span class="header-section-number">19</span> Muestreo y Distribuciones en el Muestreo</a></li>
<li><a class="" href="ex-estimacion.html"><span class="header-section-number">20</span> Estimación puntual</a></li>
<li><a class="" href="ex-intervalos.html"><span class="header-section-number">21</span> Intervalos de confianza</a></li>
<li><a class="" href="ex-contrastes.html"><span class="header-section-number">22</span> Contrastes de Hipótesis</a></li>
<li><a class="" href="ex-inferencia-aplicada.html"><span class="header-section-number">23</span> Aplicaciones de los contrastes de hipótesis</a></li>
<li><a class="" href="ex-computacion-intensiva.html"><span class="header-section-number">24</span> Bootstrap y tests de permutación</a></li>
<li><a class="" href="bibliografia.html">Bibliografia</a></li>
</ul>
<div class="book-extra"></div></nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><nav aria-label="Descargas PDF"><a href="FundamentosInferencia.pdf">Teoría (PDF)</a>
  <a href="FundamentosInferencia-Ejercicios.pdf">Ejercicios (PDF)</a>
</nav><div id="las-pruebas-chi-cuadrado" class="section level1" number="13">
<h1>
<span class="header-section-number">Capítulo 13</span> Las pruebas “Chi-cuadrado”<a class="anchor" aria-label="anchor" href="#las-pruebas-chi-cuadrado"><i class="fas fa-link"></i></a>
</h1>
<div id="introducción-8" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> Introducción<a class="anchor" aria-label="anchor" href="#introducci%C3%B3n-8"><i class="fas fa-link"></i></a>
</h2>
<p>Con el nombre de <strong>pruebas de chi-cuadrado</strong> se conoce una variedad de contrastes estadísticos que hacen referencia a problemas distintos pero que presentan los siguientes rasgos en común:</p>
<ul>
<li>Las muestras corresponden a <strong>datos categóricos</strong>, directamente o por categorización de una variable numérica; es decir, se observa si un individuo pertenece a un elemento de una partición <span class="math inline">\(A_{1}, A_{2}, \ldots, A_{k}\)</span> del espacio muestral.</li>
<li>El estadístico del contraste tiene una estructura común:</li>
</ul>
<p><span class="math display">\[
\sum_{i} \frac{(O_i - E_i)^2}{E_i}
\]</span></p>
<p>donde</p>
<ul>
<li>
<span class="math inline">\(O_i\)</span> es el número de observaciones en la categoría <span class="math inline">\(i\)</span>,</li>
<li>
<span class="math inline">\(E_i\)</span> es el número de observaciones esperadas en dicha categoría bajo la hipótesis nula.</li>
</ul>
<p>En todos los casos, el estadístico del contraste tiene <strong>distribución asintótica</strong> <span class="math inline">\(\chi^2\)</span>.</p>
<p>Consideramos tres grandes grupos de pruebas:</p>
<ol style="list-style-type: decimal">
<li>Pruebas de bondad de ajuste (<em>goodness of fit</em>):
<ol style="list-style-type: lower-alpha">
<li>todos los parámetros de la distribución son conocidos;<br>
</li>
<li>algunos parámetros de la distribución son desconocidos.</li>
</ol>
</li>
<li>Pruebas de independencia.</li>
<li>Pruebas de homogeneidad.</li>
</ol>
</div>
<div id="pruebas-chi2-de-bondad-de-ajuste" class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> Pruebas <span class="math inline">\(\chi^2\)</span> de bondad de ajuste<a class="anchor" aria-label="anchor" href="#pruebas-chi2-de-bondad-de-ajuste"><i class="fas fa-link"></i></a>
</h2>
<div id="hipótesis-simples" class="section level3" number="13.2.1">
<h3>
<span class="header-section-number">13.2.1</span> Hipótesis simples<a class="anchor" aria-label="anchor" href="#hip%C3%B3tesis-simples"><i class="fas fa-link"></i></a>
</h3>
<p>Sea <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> una <strong>muestra aleatoria simple (m.a.s.)</strong> de una variable aleatoria <span class="math inline">\(X\)</span>. Queremos contrastar la hipótesis de que <span class="math inline">\(X\)</span> sigue una distribución completamente especificada <span class="math inline">\(F_{\theta_0}\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: X \sim F_{\theta_0},\\
H_1 &amp;: X \nsim F_{\theta_0}.
\end{aligned}
\]</span></p>
<p>Sea <span class="math inline">\(R\)</span> el <strong>soporte</strong> (recorrido) de la distribución poblacional y consideremos una partición de <span class="math inline">\(R\)</span> en <span class="math inline">\(k\)</span> subconjuntos disjuntos <span class="math inline">\(R_1, R_2, \ldots, R_k\)</span>. Esto induce una partición del espacio muestral en los sucesos</p>
<p><span class="math display">\[
A_i = \{X \in R_i\}, \quad i=1,\ldots,k.
\]</span></p>
<p>Si <span class="math inline">\(n_i\)</span> denota el número de observaciones muestrales que caen en <span class="math inline">\(R_i\)</span>, el vector de recuentos <span class="math inline">\((n_1, \ldots, n_k)\)</span> sigue una distribución multinomial</p>
<p><span class="math display">\[
(n_1, \ldots, n_k) \sim M\bigl(n; p_1, \ldots, p_k\bigr),
\]</span></p>
<p>donde <span class="math inline">\(p_i = P(A_i)\)</span>.</p>
<p>Este planteamiento transforma el contraste sobre la distribución de <span class="math inline">\(X\)</span> en un contraste sobre las probabilidades <span class="math inline">\((p_1, \ldots, p_k)\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: P(A_i) = p_i^0 = \int_{R_i} dF_{\theta_0}(x),\\
H_1 &amp;: P(A_i) \neq p_i^0.
\end{aligned}
\]</span></p>
<p>Obsérvese que <strong>no se contrasta</strong> que el vector de recuentos tenga distribución multinomial (esto viene dado por el muestreo), sino si las probabilidades <span class="math inline">\(p_i\)</span> coinciden con las impuestas por la hipótesis nula.</p>
</div>
<div id="estadístico-de-pearson" class="section level3" number="13.2.2">
<h3>
<span class="header-section-number">13.2.2</span> Estadístico de Pearson<a class="anchor" aria-label="anchor" href="#estad%C3%ADstico-de-pearson"><i class="fas fa-link"></i></a>
</h3>
<p>A comienzos del siglo XX, <strong>Karl Pearson</strong> propuso como estadístico de contraste la cantidad</p>
<p><span class="math display">\[
D^2 = \sum_{i=1}^k \frac{(n_i - n p_i^0)^2}{n p_i^0}.
\]</span></p>
<p>Este estadístico mide la discrepancia entre las frecuencias observadas y las esperadas bajo <span class="math inline">\(H_0\)</span>. Su interés fundamental radica en que se conoce su distribución asintótica bajo la hipótesis nula.</p>
<div id="teorema-pearson" class="section level4" number="13.2.2.1">
<h4>
<span class="header-section-number">13.2.2.1</span> Teorema (Pearson)<a class="anchor" aria-label="anchor" href="#teorema-pearson"><i class="fas fa-link"></i></a>
</h4>
<p>Si las probabilidades <span class="math inline">\(p_1^0, \ldots, p_k^0\)</span> son conocidas, entonces</p>
<p><span class="math display">\[
D^2 \xrightarrow[n\to\infty]{\mathcal{L}} \chi^2_{k-1}.
\]</span></p>
<p>Este resultado permite construir un contraste asintótico de nivel <span class="math inline">\(\alpha\)</span> que rechaza <span class="math inline">\(H_0\)</span> cuando</p>
<p><span class="math display">\[
D^2 \ge \chi^2_{k-1,1-\alpha}.
\]</span></p>
</div>
</div>
<div id="observaciones-prácticas" class="section level3" number="13.2.3">
<h3>
<span class="header-section-number">13.2.3</span> Observaciones prácticas<a class="anchor" aria-label="anchor" href="#observaciones-pr%C3%A1cticas"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>El contraste es <strong>asintótico</strong>, por lo que se requiere un tamaño muestral suficientemente grande. En la práctica se exige que todas las frecuencias esperadas cumplan <span class="math inline">\(n p_i^0 \ge 5\)</span>.</li>
<li>El contraste depende de la partición elegida. Conviene tomar <span class="math inline">\(k \ge 5\)</span> siempre que sea posible para evitar situaciones poco discriminantes.</li>
</ul>
</div>
<div id="ejemplo-1-bondad-de-ajuste" class="section level3" number="13.2.4">
<h3>
<span class="header-section-number">13.2.4</span> Ejemplo 1: Bondad de ajuste<a class="anchor" aria-label="anchor" href="#ejemplo-1-bondad-de-ajuste"><i class="fas fa-link"></i></a>
</h3>
<p>Una compañía afirma que el número diario de accidentes laborales sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda=2\)</span>. Un estudio, basado en los accidentes producidos durante 200 días, da el resultado siguiente:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">
<span class="math inline">\(N^{\underline{O}}\)</span> de accidentes</th>
<th align="center">0</th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
<th align="center">5</th>
<th align="center">6</th>
<th align="center">7</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">Días</td>
<td align="center">22</td>
<td align="center">53</td>
<td align="center">58</td>
<td align="center">39</td>
<td align="center">20</td>
<td align="center">5</td>
<td align="center">2</td>
<td align="center">1</td>
</tr></tbody>
</table></div>
<p>Para contrastar el ajuste a una distribución de Poisson debemos calcular las probabilidades</p>
<p><span class="math display">\[
p_{i}^{0}=P_{\lambda=2}[X=i]=e^{-\lambda} \frac{\lambda^{i}}{i!}, \quad i=1, \ldots, 7 .
\]</span></p>
<p>Las frecuencias esperadas serán <span class="math inline">\(n p_{i}^{0}=200 p_{i}^{0}\)</span>. Cuando <span class="math inline">\(i=6,7\)</span> los valores son demasiado pequeños, de forma que se agrupan los valores en una única categoría “<span class="math inline">\(i \geq 5\)</span>”.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
</colgroup>
<thead><tr class="header">
<th align="left"><span class="math inline">\(x_{i}\)</span></th>
<th align="left">0</th>
<th align="left">1</th>
<th align="left">2</th>
<th align="left">3</th>
<th align="left">4</th>
<th align="left"><span class="math inline">\(\geq 5\)</span></th>
<th align="left"><span class="math inline">\(\Sigma\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(n_{i}\)</span></td>
<td align="left">22</td>
<td align="left">53</td>
<td align="left">58</td>
<td align="left">39</td>
<td align="left">20</td>
<td align="left">8</td>
<td align="left">200</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(p_{i}^{0}\)</span></td>
<td align="left">0.135</td>
<td align="left">0.271</td>
<td align="left">0.271</td>
<td align="left">0.180</td>
<td align="left">0.090</td>
<td align="left">0.053</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n p_{i}^{0}\)</span></td>
<td align="left">27.067</td>
<td align="left">54.134</td>
<td align="left">54.134</td>
<td align="left">36.089</td>
<td align="left">18.045</td>
<td align="left">10.531</td>
<td align="left">200</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\frac{\left(n p_{i}^{0}-n_{i}\right)^{2}}{n p_{i}^{0}}\)</span></td>
<td align="left">0.9486</td>
<td align="left">0.0238</td>
<td align="left">0.2761</td>
<td align="left">0.2347</td>
<td align="left">0.2119</td>
<td align="left">0.6081</td>
<td align="left">2.303</td>
</tr>
</tbody>
</table></div>
<p>El valor del estadístico de test es, por tanto, 2.303. El <span class="math inline">\(p\)</span>-valor correspondiente, es decir, <span class="math inline">\(P\left(\chi_{6-1}^{2} \geq 2.303\right)\)</span>, es 0.80588 y, por tanto, no podemos rechazar la hipótesis de que los datos siguen una distribución de Poisson de parámetro <span class="math inline">\(\lambda=2\)</span>. Otra forma de tomar la misma decisión es observar que el percentil 0.95 de dicha distribución es <span class="math inline">\(\chi_{5,0.95}^{2}=11.07\)</span>, de donde, dado que <span class="math inline">\(2.303&lt;\chi_{5,0.95}^{2}\)</span>, vemos que no podemos rechazar <span class="math inline">\(H_{0}\)</span>.</p>
</div>
<div id="ejemplo-2-ajuste-de-modelo-genético" class="section level3" number="13.2.5">
<h3>
<span class="header-section-number">13.2.5</span> Ejemplo 2: Ajuste de modelo genético<a class="anchor" aria-label="anchor" href="#ejemplo-2-ajuste-de-modelo-gen%C3%A9tico"><i class="fas fa-link"></i></a>
</h3>
<p>Un cierto modelo genético para unas plantas cuyas flores pueden ser blancas, rosas o rojas afirma que la proporción con la que deben aparecer es de <span class="math inline">\(1:2:1\)</span>. En un estudio se obtuvieron 112 flores blancas, 242 rosas y 112 rojas. ¿Concuerdan las observaciones con el modelo? Construimos la tabla de cálculos y obtenemos:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="16%">
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
</colgroup>
<thead><tr class="header">
<th align="left"><span class="math inline">\(A_{i}\)</span></th>
<th align="center">Blanca</th>
<th align="center">Rosa</th>
<th align="center">Rojas</th>
<th align="center"><span class="math inline">\(\Sigma\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(n_{i}\)</span></td>
<td align="center">112</td>
<td align="center">242</td>
<td align="center">112</td>
<td align="center">467</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(p_{i}^{0}\)</span></td>
<td align="center">0.25</td>
<td align="center">0.5</td>
<td align="center">0.25</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n p_{i}^{0}\)</span></td>
<td align="center">116.7</td>
<td align="center">233</td>
<td align="center">116.7</td>
<td align="center">467</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\frac{\left(n p_{i}^{0}-n_{i}\right)^{2}}{n p_{i}^{0}}\)</span></td>
<td align="center">0.117</td>
<td align="center">0.348</td>
<td align="center">0.193</td>
<td align="center"><span class="math inline">\(\mathbf{0 . 6 5 7}\)</span></td>
</tr>
</tbody>
</table></div>
<p>El valor crítico es el percentil de una distribución ji-cuadrado con dos grados de libertad, <span class="math inline">\(\chi_{2,0.95}^{2}=5.99\)</span>, de donde, dado que <span class="math inline">\(0.657&lt;\chi_{2,0.95}^{2}\)</span>, vemos que no podemos rechazar <span class="math inline">\(H_{0}\)</span>.</p>
<p>Obsérvese que el primer ejemplo corresponde a una variable numérica que se ha categorizado, mientras que el segundo se refiere directamente a una distribución multinomial.</p>
</div>
<div id="hipótesis-compuestas" class="section level3" number="13.2.6">
<h3>
<span class="header-section-number">13.2.6</span> Hipótesis compuestas<a class="anchor" aria-label="anchor" href="#hip%C3%B3tesis-compuestas"><i class="fas fa-link"></i></a>
</h3>
<p>El test de ajuste que hemos discutido en la sección anterior corresponde a una situación poco habitual. En la práctica, lo que nos interesará es decidir si los datos se ajustan a una determinada familia de distribuciones. Por ejemplo, antes de aplicar un test en el que se supone que los datos siguen una ley Normal, hay que verificar hasta qué punto es válida esta suposición.</p>
<p>En este caso nos encontramos en una situación análoga a la anterior, salvo por el hecho de que la distribución no está completamente especificada sino que depende de un parámetro <span class="math inline">\(m\)</span>-dimensional.</p>
<p><span class="math display">\[
\begin{aligned}
X &amp; \sim F_{\theta},\left(\theta \in \Theta \subset \mathbb{R}^{m}\right) \\
R &amp; =\operatorname{Rec}(X)=\biguplus_{i=1}^{k} R_{i}, \quad A_{i}=\left\{X \in R_{i}\right\}, P\left(A_{i}\right)=p_{i}(\theta) \Longrightarrow \\
Y &amp; =\left(n_{1}, \ldots, n_{k}\right), n_{i}=\# A_{i} \quad Y \sim M\left(n ; \mathbf{p}=\left(p_{1}(\theta), \ldots, p_{k}(\theta)\right)\right) .
\end{aligned}
\]</span></p>
<p>Una primera idea que se nos podría ocurrir para abordar este problema sería estimar <span class="math inline">\(\theta\)</span> mediante un estimador <span class="math inline">\(\hat{\theta}\)</span> y sustituir <span class="math inline">\(p_{i}^{0}\)</span> por <span class="math inline">\(p_{i}(\hat{\theta})\)</span> en (7.1). Esto no sería mala idea si la estimación se basase en una muestra distinta de la que se usa para realizar el ajuste.</p>
<p>Ahora bien, este no es el caso aquí. Si usamos la muestra para estimar los parámetros y después hacemos el ajuste, estamos “forzando la muestra” a seleccionar la distribución poblacional para que se ajuste bien a la muestra a través de la estimación de los parámetros (estamos haciendo un ajuste condicionado). Para compensarlo, intentaremos ser “más exigentes” a la hora de juzgar si las frecuencias observadas se corresponden con las esperadas, y eso se reflejará en que, en lugar de basarnos en una distribución <span class="math inline">\(\chi^{2}\)</span> con <span class="math inline">\(k-1\)</span> grados de libertad, lo haremos en una con <span class="math inline">\(k-1-m\)</span> grados de libertad, donde <span class="math inline">\(m\)</span> representará el número de parámetros que hemos tenido que estimar. Este resultado se expresa en el teorema siguiente:</p>
<p><strong>Teorema:</strong> <em>Bajo las condiciones del teorema 1 supongamos que las probabilidades <span class="math inline">\(p_{1}, \ldots, p_{k}\)</span> dependen de parámetros desconocidos <span class="math inline">\(\theta=\theta_{1}, \ldots, \theta_{m}\)</span>. Sean <span class="math inline">\(\hat{\theta}=\hat{\theta}_{1}, \ldots, \hat{\theta}_{m}\)</span> las estimaciones de máxima verosimilitud de los parámetros <span class="math inline">\(\theta\)</span> y supongamos que se verifican las siguientes condiciones de regularidad:</em></p>
<ol style="list-style-type: decimal">
<li>Las derivadas parciales <span class="math inline">\(\frac{\partial p_{i}}{\partial \theta_{j}}, \frac{\partial^{2} p_{i}}{\partial \theta_{i} \partial \theta_{j}}\)</span> existen y son continuas.</li>
<li>La matriz jacobiana <span class="math inline">\(\frac{\partial p_{i}}{\partial \theta_{j}}\)</span>, <span class="math inline">\(i=1, \ldots, k\)</span>, <span class="math inline">\(j=1, \ldots, m\)</span>, tiene rango <span class="math inline">\(m\)</span>.</li>
</ol>
<p>Entonces el estadístico</p>
<p><span class="math display">\[
D^{2}=\sum_{i=1}^{k} \frac{\left(n_{i}-n p_{i}(\hat{\theta})\right)^{2}}{n p_{i}(\hat{\theta})}
\]</span></p>
<p>verifica</p>
<p><span class="math display">\[
D^{2} \xrightarrow[n \rightarrow \infty]{£} \chi_{k-1-\operatorname{dim}(\Theta)}^{2}
\]</span></p>
<p>es decir, tiene distribución asintótica <span class="math inline">\(\chi^{2}\)</span> con <span class="math inline">\(k-1-\operatorname{dim}(\Theta)\)</span> grados de libertad.</p>
<p>Podemos proceder de forma análoga al caso de probabilidades conocidas para establecer el test siguiente:</p>
<p><strong>Definición 7.2</strong> Test de bondad de ajuste cuando hay que estimar parámetros</p>
<p>Sean:</p>
<p><span class="math display">\[
\begin{aligned}
X &amp; \sim F_{\theta},\left(\theta \in \Theta \subset \Re^{m}\right) \quad R: \operatorname{Rec}(X)=\biguplus_{i=1}^{k} R_{i} \\
A_{i} &amp; =\left\{X \in R_{i}\right\}, P\left(A_{i}\right)=p_{i}(\theta) \\
Y &amp; =\left(n_{1}, \ldots, n_{k}\right), n_{i}=\# A_{i}, \quad Y \sim M\left(n ; \mathbf{p}=\left(p_{1}(\theta), \ldots, p_{k}(\theta)\right)\right) .
\end{aligned}
\]</span></p>
<p>Entonces, para contrastar las hipótesis:</p>
<p><span class="math display">\[
\begin{array}{ll}
H_{0}: &amp; X \sim F_{\theta}^{0} \Leftrightarrow \mathbf{p}=\left(p_{1}(\theta), \ldots, p_{k}(\theta)\right) \\
H_{1}: &amp; \mathbf{p} \neq\left(p_{1}(\theta), \ldots, p_{k}(\theta)\right)
\end{array}
\]</span></p>
<p>el test consiste en rechazar <span class="math inline">\(H_{0}\)</span> si <span class="math inline">\(D^{2} \geq \chi_{k-1-\operatorname{dim}(\Theta), 1-\alpha}^{2}\)</span>, donde</p>
<p><span class="math display">\[
\begin{aligned}
D^{2}= &amp; \sum_{i=1}^{k} \frac{\left(n_{i}-n p_{i}(\hat{\theta})\right)^{2}}{n p_{i}(\hat{\theta})} \\
D^{2} &amp; \underset{n \rightarrow \infty}{\stackrel{£}{\rightarrow}} \chi_{k-1-\operatorname{dim}(\Theta)}^{2}
\end{aligned}
\]</span></p>
<p>es un test asintótico de nivel <span class="math inline">\(\alpha\)</span>.
Este resultado establece que una región crítica para el test 7.2 tendrá la forma</p>
<p><span class="math display">\[
W=\left\{D^{2} \geq \chi_{k-1-\operatorname{dim}(\Theta), 1-\alpha}^{2}\right\}
\]</span></p>
<p>donde <span class="math inline">\(\chi_{k-1,1-\alpha}^{2}\)</span> es el cuantil <span class="math inline">\(1-\alpha\)</span> de una distribución <span class="math inline">\(\chi^{2}\)</span> con <span class="math inline">\(k-1-\operatorname{dim}(\Theta)\)</span> grados de libertad.</p>
</div>
<div id="ejemplo-3-ajuste-de-modelo-genético-con-probabilidades-desconocidas" class="section level3" number="13.2.7">
<h3>
<span class="header-section-number">13.2.7</span> Ejemplo 3: Ajuste de modelo genético con probabilidades desconocidas<a class="anchor" aria-label="anchor" href="#ejemplo-3-ajuste-de-modelo-gen%C3%A9tico-con-probabilidades-desconocidas"><i class="fas fa-link"></i></a>
</h3>
<p>En el ejemplo anterior, cuando hemos ajustado unos datos a unas proporciones del tipo “1:2:1” o “9:3:3:1” estábamos suponiendo dos cosas:</p>
<ul>
<li>Un modelo genético (que no tenemos por qué conocer)</li>
<li>Unas probabilidades fijadas.</li>
</ul>
<p>Esto lo hemos sintetizado en un vector numérico <span class="math inline">\(\left(p_{1}^{0}, \ldots, p_{k}^{0}\right)\)</span>. Por ejemplo, en (7.2.2) la proporción “1:2:1” viene de suponer:</p>
<ul>
<li>Como modelo: <span class="math inline">\(p^{2}, 2 p(1-p), q^{2}\)</span>,</li>
<li>Como probabilidades: <span class="math inline">\(p=\frac{1}{2}\)</span>.</li>
</ul>
<p>A menudo nos interesa ajustar solo el modelo, es decir, decidir si, por ejemplo, el modelo <span class="math inline">\(p^{2}, 2 p(1-p), q^{2}\)</span> describe bien los datos observados para algún <span class="math inline">\(p \in(0,1)\)</span>. En este caso, antes de comparar los observados <span class="math inline">\(n_{i}\)</span> con los esperados <span class="math inline">\(p_{i}\)</span>, tendremos que estimar los valores de los <span class="math inline">\(p_{i}\)</span>.</p>
<p>Bajo la suposición de un modelo multinomial,</p>
<p><span class="math display">\[
\begin{array}{ll}
Y \sim M(n, \mathbf{p}(\theta), &amp; \theta=p, \\
&amp; p_{1}(\theta)=p^{2}, p_{2}(\theta)=2 p(1-p), p_{3}(\theta)=(1-p)^{2}
\end{array}
\]</span></p>
<p>la verosimilitud del modelo es:</p>
<p><span class="math display">\[
L\left(n_{1}, \ldots, n_{k} ; \mathbf{p}(\theta)\right) \propto\left(p^{2}\right)^{n_{1}} \cdot(2 p(1-p))^{n_{2}} \cdot\left(q^{2}\right)^{n_{3}}
\]</span></p>
<p>Una aplicación rutinaria del método de máxima verosimilitud da como estimador de máxima verosimilitud de <span class="math inline">\(p\)</span>:</p>
<p><span class="math display">\[
\hat{p}_{M V}=\frac{2 n_{1}+n_{2}}{2 n_{1}+2 n_{2}+2 n_{3}}
\]</span></p>
<p>Supongamos ahora que tenemos unos datos genéticos correspondientes al grupo sanguíneo <span class="math inline">\(M-N\)</span> en una población de 6129 individuos, indios navajos, que son los siguientes:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Grupo</th>
<th align="center"><span class="math inline">\(M\)</span></th>
<th align="center"><span class="math inline">\(M-N\)</span></th>
<th align="center"><span class="math inline">\(N\)</span></th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">Individuos</td>
<td align="center">1787</td>
<td align="center">3039</td>
<td align="center">1303</td>
</tr></tbody>
</table></div>
<p>El estimador de máxima verosimilitud calculado sobre los datos del ejemplo es:</p>
<p><span class="math display">\[
\hat{p}_{M V}=\frac{2 \cdot 1787+3039}{2 \cdot 1787+2 \cdot 3039+2 \cdot 1303}=0.539
\]</span></p>
<p>de donde la tabla con los valores observados y esperados para hacer el test de ajuste es:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="left">M</th>
<th align="left"><span class="math inline">\(M-N\)</span></th>
<th align="left"><span class="math inline">\(N\)</span></th>
<th align="left"><span class="math inline">\(\Sigma\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(n_{i}\)</span></td>
<td align="left">1787</td>
<td align="left">3039</td>
<td align="left">1303</td>
<td align="left">6129</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(p_{i}\left(\hat{p}_{M V}\right)\)</span></td>
<td align="left">0.539</td>
<td align="left">2. 0.539. 0.461</td>
<td align="left">0.461</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n p_{i}\left(\hat{p}_{M V}\right)\)</span></td>
<td align="left">1784</td>
<td align="left">3046</td>
<td align="left">1299.8</td>
<td align="left">6129</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\frac{\left(n p_{i}\left(\hat{p}_{M V}\right)-n_{i}\right)^{2}}{n p_{i}\left(\hat{p}_{M V}\right)}\)</span></td>
<td align="left">0.0067</td>
<td align="left">0.0166</td>
<td align="left">0.0078</td>
<td align="left">0.0311</td>
</tr>
</tbody>
</table></div>
<p>El valor crítico es el percentil de una distribución ji-cuadrado con dos menos un grados de libertad, <span class="math inline">\(\chi_{1,0.95}^{2}=3.841\)</span>, de donde, dado que <span class="math inline">\(0.0311&lt;\chi_{1,0.95}^{2}\)</span>, vemos que no podemos rechazar <span class="math inline">\(H_{0}\)</span>.</p>
</div>
<div id="ejemplo-4-ajuste-a-una-distribución-normal" class="section level3" number="13.2.8">
<h3>
<span class="header-section-number">13.2.8</span> Ejemplo 4: Ajuste a una distribución normal<a class="anchor" aria-label="anchor" href="#ejemplo-4-ajuste-a-una-distribuci%C3%B3n-normal"><i class="fas fa-link"></i></a>
</h3>
<p>En un estudio sobre bilingüismo se aplicó una prueba a una muestra de 211 alumnos y se obtuvieron 211 puntuaciones que, una vez tabuladas, eran las siguientes:</p>
<div class="inline-table"><table style="width:100%;" class="table table-sm">
<colgroup>
<col width="10%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
</colgroup>
<thead><tr class="header">
<th align="left">Puntuación</th>
<th align="center"><span class="math inline">\((\leq 55]\)</span></th>
<th align="center"><span class="math inline">\((55-60]\)</span></th>
<th align="center"><span class="math inline">\((60-65]\)</span></th>
<th align="center"><span class="math inline">\((65-70]\)</span></th>
<th align="center"><span class="math inline">\((70-75]\)</span></th>
<th align="center"><span class="math inline">\((75-80]\)</span></th>
<th align="center"><span class="math inline">\((80-85]\)</span></th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">Frecuencia</td>
<td align="center">4</td>
<td align="center">17</td>
<td align="center">45</td>
<td align="center">67</td>
<td align="center">53</td>
<td align="center">15</td>
<td align="center">10</td>
</tr></tbody>
</table></div>
<p>¿Podemos aceptar la hipótesis de que la puntuación sigue una distribución normal? Fijémonos en que aquí no nos interesa más que el hecho de que sea normal, no una normal en concreto. Es decir, tenemos:</p>
<p><span class="math display">\[
\begin{array}{ll}
H_{0}: &amp; X \sim N(\mu, \sigma) \\
H_{1}: &amp; X \nsim N(\mu, \sigma) .
\end{array}
\]</span></p>
<p>En primer lugar estimamos los parámetros:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{\mu} &amp; =\bar{X}=68.52 \\
\hat{\sigma}^{2} &amp; =S^{2}=6.44
\end{aligned}
\]</span></p>
<p>Cada categoría <span class="math inline">\(A_{i}\)</span> es un intervalo del recorrido de la variable: <span class="math inline">\(A_{1}=X \in (-\infty, 55]\)</span>, <span class="math inline">\(A_{2}=X \in(55,60] \ldots\)</span>, de manera que si <span class="math inline">\(A_{i}=(a, b]\)</span>, las probabilidades <span class="math inline">\(p_{i}=P\left(A_{i}\right)\)</span> se calcularán, si suponemos que <span class="math inline">\(Y\)</span> representa una variable con distribución normal de media <span class="math inline">\(\hat{\mu}=\bar{x}\)</span> y desviación típica <span class="math inline">\(\hat{\sigma}=s^{2}\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
p_{i}=p_{i}\left(\bar{x}, s^{2}\right) &amp; =P_{\bar{x}, s^{2}}\left(X \in A_{i}\right)=F_{Y}(b)-F_{Y}(a) \\
&amp; =\Phi\left(\frac{b-\bar{x}}{s}\right)-\Phi\left(\frac{a-\bar{x}}{s}\right),
\end{aligned}
\]</span></p>
<p>donde <span class="math inline">\(\Phi\)</span> es la función de distribución de una variable <span class="math inline">\(N(0,1)\)</span>. Si calculamos las probabilidades en esos intervalos y construimos la tabla, obtenemos:</p>
<div class="inline-table"><table style="width:100%;" class="table table-sm">
<colgroup>
<col width="10%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
</colgroup>
<thead><tr class="header">
<th align="left">Puntuación</th>
<th align="center"><span class="math inline">\((\leq 55]\)</span></th>
<th align="center"><span class="math inline">\((55-60]\)</span></th>
<th align="center"><span class="math inline">\((60-65]\)</span></th>
<th align="center"><span class="math inline">\((65-70]\)</span></th>
<th align="center"><span class="math inline">\((70-75]\)</span></th>
<th align="center"><span class="math inline">\((75-80]\)</span></th>
<th align="center"><span class="math inline">\((\geq 80)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(n_{i}\)</span></td>
<td align="center">4</td>
<td align="center">17</td>
<td align="center">45</td>
<td align="center">67</td>
<td align="center">53</td>
<td align="center">15</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(p_{i}\left(\bar{x}, s^{2}\right)\)</span></td>
<td align="center">0.01786</td>
<td align="center">0.07556</td>
<td align="center">0.19774</td>
<td align="center">0.29979</td>
<td align="center">0.2528</td>
<td align="center">0.11871</td>
<td align="center">0.03654</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(n \cdot p_{i}\left(\bar{x}, s^{2}\right)\)</span></td>
<td align="center">3.77</td>
<td align="center">15.94</td>
<td align="center">41.72</td>
<td align="center">63.26</td>
<td align="center">53.34</td>
<td align="center">25.05</td>
<td align="center">7.92</td>
</tr>
</tbody>
</table></div>
<p>Antes de calcular el valor del estadístico de test hay que fusionar las dos primeras columnas, ya que la frecuencia esperada es inferior a 5. La tabla final queda:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="11%">
<col width="14%">
<col width="14%">
<col width="14%">
<col width="14%">
<col width="14%">
<col width="14%">
</colgroup>
<thead><tr class="header">
<th align="left">Puntuación</th>
<th align="center"><span class="math inline">\((\leq 60]\)</span></th>
<th align="center"><span class="math inline">\((60-65]\)</span></th>
<th align="center"><span class="math inline">\((65-70]\)</span></th>
<th align="center"><span class="math inline">\((70-75]\)</span></th>
<th align="center"><span class="math inline">\((75-80]\)</span></th>
<th align="center"><span class="math inline">\((\geq 80)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(n_{i}\)</span></td>
<td align="center"><span class="math inline">\(4+17\)</span></td>
<td align="center">45</td>
<td align="center">67</td>
<td align="center">53</td>
<td align="center">15</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(n \cdot p_{i}\left(\bar{x}, s^{2}\right)\)</span></td>
<td align="center"><span class="math inline">\(3.77+15.94\)</span></td>
<td align="center">41.72</td>
<td align="center">63.26</td>
<td align="center">53.34</td>
<td align="center">25.05</td>
<td align="center">7.92</td>
</tr>
</tbody>
</table></div>
<p>El estadístico de test, <span class="math inline">\(D^{2}\)</span>, vale aquí: 5.144. Como hemos estimado 2 parámetros y la tabla final tiene 6 columnas, obtendremos el valor crítico de una <span class="math inline">\(\chi^{2}\)</span> con <span class="math inline">\(6-2-1\)</span> grado de libertad. En concreto: rechazaremos <span class="math inline">\(H_{0}\)</span> si <span class="math inline">\(D^{2}&gt;\chi_{(3,0.05)}^{2}\)</span>. Como esto no ocurre, no podemos rechazar <span class="math inline">\(H_{0}\)</span>.</p>
</div>
</div>
<div id="pruebas-de-independencia-en-tablas-de-contingencia" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> Pruebas de independencia en tablas de contingencia<a class="anchor" aria-label="anchor" href="#pruebas-de-independencia-en-tablas-de-contingencia"><i class="fas fa-link"></i></a>
</h2>
<p>Sea <span class="math inline">\(\Omega\)</span> una población que admite dos descomposiciones diferentes en eventos excluyentes. Por ejemplo, una descomposición puede hacerse por sexo (hombres/mujeres) y la otra por tabaquismo (fumadores/no fumadores).</p>
<p><span class="math display">\[
\Omega=A_{1} \biguplus \cdots \biguplus A_{k}=B_{1} \biguplus \cdots \biguplus B_{r},
\]</span></p>
<p>donde el símbolo <span class="math inline">\(\biguplus\)</span> indica unión disjunta. Supongamos que se realizan <span class="math inline">\(n\)</span> observaciones o pruebas independientes, de modo que <span class="math inline">\(n_{ij}\)</span> representa la frecuencia con la que se presenta el evento <span class="math inline">\(A_i \cap B_j\)</span>. Podemos disponer las observaciones en una tabla cruzada o de contingencia de <span class="math inline">\(r\)</span> filas por <span class="math inline">\(k\)</span> columnas:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="left"><span class="math inline">\(A_{1}\)</span></th>
<th align="left"><span class="math inline">\(\cdots\)</span></th>
<th align="left"><span class="math inline">\(A_{k}\)</span></th>
<th align="left"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(\mathrm{B}_{1}\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{11}\)</span></td>
<td align="left"><span class="math inline">\(\cdots\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{1k}\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{1\cdot}\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"><span class="math inline">\(\ddots\)</span></td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\mathrm{B}_{r}\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{r1}\)</span></td>
<td align="left"><span class="math inline">\(\cdots\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{rk}\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{r\cdot}\)</span></td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{\cdot 1}\)</span></td>
<td align="left"></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{\cdot k}\)</span></td>
<td align="left"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table></div>
<p>donde <span class="math inline">\(n_{i\cdot}=\sum_{j=1}^{k} n_{ij}\)</span> es la frecuencia del evento <span class="math inline">\(A_i\)</span> y <span class="math inline">\(n_{\cdot j}=\sum_{i=1}^{r} n_{ij}\)</span> es la frecuencia del evento <span class="math inline">\(B_j\)</span>.</p>
<p>Supongamos que queremos contrastar la hipótesis de que las dos particiones son independientes, es decir,</p>
<p><span class="math display">\[
H_{0}: \quad A_i \text{ es estocásticamente independiente de } B_j,
\]</span></p>
<p>lo que equivale a</p>
<p><span class="math display">\[
P(A_i \cap B_j)=P(A_i)\,P(B_j), \quad i=1,\ldots,k,\; j=1,\ldots,r.
\]</span></p>
<p>Si indicamos <span class="math inline">\(p_{ij}=P(A_i \cap B_j)\)</span> e introducimos los parámetros</p>
<p><span class="math display">\[
p_{1\cdot},\ldots,p_{r\cdot},\quad \sum_{i=1}^{r} p_{i\cdot}=1,\qquad
p_{\cdot 1},\ldots,p_{\cdot k},\quad \sum_{j=1}^{k} p_{\cdot j}=1,
\]</span></p>
<p>la hipótesis nula se expresará como</p>
<p><span class="math display">\[
p_{ij}=p_{i\cdot}\,p_{\cdot j}.
\]</span></p>
<p>Es fácil ver que, en este caso, los estimadores de máxima verosimilitud de las probabilidades marginales son las frecuencias relativas:</p>
<p><span class="math display">\[
\hat p_{i\cdot}=\frac{n_{i\cdot}}{n}, \qquad \hat p_{\cdot j}=\frac{n_{\cdot j}}{n},
\]</span></p>
<p>y la frecuencia esperada del evento <span class="math inline">\(A_i \cap B_j\)</span> bajo <span class="math inline">\(H_0\)</span> será</p>
<p><span class="math display">\[
n\,\hat p_{i\cdot}\,\hat p_{\cdot j}
= n\,\frac{n_{i\cdot}}{n}\,\frac{n_{\cdot j}}{n}
= \frac{n_{i\cdot}\,n_{\cdot j}}{n}.
\]</span></p>
<p>Aplicando el Teorema 7.2 se tiene que el estadístico</p>
<p><span class="math display">\[
D^{2}=\sum_{i=1}^{k}\sum_{j=1}^{r}
\frac{\left(n_{ij}-\frac{n_{i\cdot}n_{\cdot j}}{n}\right)^{2}}
{\frac{n_{i\cdot}n_{\cdot j}}{n}}
\]</span></p>
<p>verifica</p>
<p><span class="math display">\[
D^{2}\xrightarrow[n\to\infty]{\mathcal{L}} \chi^{2}_{(r-1)(k-1)}.
\]</span></p>
<p>Como consecuencia, el test de independencia para la hipótesis</p>
<p><span class="math display">\[
H_{0}: \quad P(A_i\cap B_j)=P(A_i)\,P(B_j)
\;\Longleftrightarrow\;
p_{ij}=p_{i\cdot}\,p_{\cdot j}
\]</span></p>
<p>consiste en calcular</p>
<p><span class="math display">\[
D^{2}=\sum_{i=1}^{k}\sum_{j=1}^{r}
\frac{\left(n_{ij}-\frac{n_{i\cdot}n_{\cdot j}}{n}\right)^{2}}
{\frac{n_{i\cdot}n_{\cdot j}}{n}}
\]</span></p>
<p>y rechazar <span class="math inline">\(H_{0}\)</span> si</p>
<p><span class="math display">\[
D^{2}\ge \chi^{2}_{(k-1)(r-1),\,1-\alpha}.
\]</span></p>
<div id="ejemplo-5-relación-entre-nivel-de-estudios-y-preferencias" class="section level3" number="13.3.1">
<h3>
<span class="header-section-number">13.3.1</span> Ejemplo 5: Relación entre nivel de estudios y preferencias<a class="anchor" aria-label="anchor" href="#ejemplo-5-relaci%C3%B3n-entre-nivel-de-estudios-y-preferencias"><i class="fas fa-link"></i></a>
</h3>
<p>En un estudio de mercado se intenta determinar si existe alguna relación entre las preferencias de un grupo de consumidores por un tipo de vehículo y su nivel cultural. Se pregunta a 300 personas entre 20 y 50 años qué vehículo poseen y se clasifican en “NINGUNO”, “MOTOCICLETAS”, “COCHES NORMALES” y “COCHES POTENTES”. El nivel cultural se determina según hayan cursado estudios “ELEMENTALES”, “DE GRADO MEDIO” o “SUPERIORES”. ¿Qué se puede concluir a partir de los siguientes datos?</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="center"></th>
<th align="center">NINGUNO</th>
<th align="center">MOTOS</th>
<th align="center">C. NORMAL</th>
<th align="center">C. POTENTE</th>
<th align="center">TOTAL</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">Elementales</td>
<td align="center">31</td>
<td align="center">49</td>
<td align="center">18</td>
<td align="center">12</td>
<td align="center">110</td>
</tr>
<tr class="even">
<td align="center">Nivel medio</td>
<td align="center">11</td>
<td align="center">59</td>
<td align="center">26</td>
<td align="center">25</td>
<td align="center">121</td>
</tr>
<tr class="odd">
<td align="center">Superiores</td>
<td align="center">12</td>
<td align="center">51</td>
<td align="center">31</td>
<td align="center">36</td>
<td align="center">130</td>
</tr>
<tr class="even">
<td align="center">TOTAL</td>
<td align="center">54</td>
<td align="center">159</td>
<td align="center">75</td>
<td align="center">73</td>
<td align="center">361</td>
</tr>
</tbody>
</table></div>
<p>La tabla de frecuencias esperadas es:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="center"></th>
<th align="center">NINGUNO</th>
<th align="center">MOTOS</th>
<th align="center">C. NORMAL</th>
<th align="center">C. POTENTE</th>
<th align="center">TOTAL</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">Elementales</td>
<td align="center">16.5</td>
<td align="center">48.4</td>
<td align="center">22.9</td>
<td align="center">22.2</td>
<td align="center">110</td>
</tr>
<tr class="even">
<td align="center">Nivel medio</td>
<td align="center">18.1</td>
<td align="center">53.3</td>
<td align="center">25.1</td>
<td align="center">24.5</td>
<td align="center">121</td>
</tr>
<tr class="odd">
<td align="center">Superiores</td>
<td align="center">19.4</td>
<td align="center">57.3</td>
<td align="center">27.0</td>
<td align="center">26.3</td>
<td align="center">130</td>
</tr>
<tr class="even">
<td align="center">TOTAL</td>
<td align="center">54</td>
<td align="center">159</td>
<td align="center">75</td>
<td align="center">73</td>
<td align="center">361</td>
</tr>
</tbody>
</table></div>
<p>El valor del estadístico de contraste <span class="math inline">\(D^{2}\)</span> calculado sobre estos datos es 29.76. El valor crítico de una distribución <span class="math inline">\(\chi^2\)</span> con <span class="math inline">\((4-1)(3-1)=6\)</span> grados de libertad y nivel de significación 0.05 es 12.59. Dado que</p>
<p><span class="math display">\[
29.76 \ge 12.59=\chi^{2}_{(3-1)(4-1),\,1-0.05},
\]</span></p>
<p>se rechaza la hipótesis de independencia; es decir, parece existir relación entre el nivel de estudios y el tipo de vehículo.</p>
</div>
</div>
<div id="pruebas-de-homogeneidad" class="section level2" number="13.4">
<h2>
<span class="header-section-number">13.4</span> Pruebas de homogeneidad<a class="anchor" aria-label="anchor" href="#pruebas-de-homogeneidad"><i class="fas fa-link"></i></a>
</h2>
<p>Supongamos que tenemos una misma partición</p>
<p><span class="math display">\[
\Omega=A_{1} \biguplus \cdots \biguplus A_{k},
\]</span></p>
<p>en <span class="math inline">\(r\)</span> poblaciones:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
<col width="20%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="left"><span class="math inline">\(A_{1}\)</span></th>
<th align="left"><span class="math inline">\(\cdots\)</span></th>
<th align="left"><span class="math inline">\(A_{k}\)</span></th>
<th align="left"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left"><span class="math inline">\(\mathrm{n}_{11}\)</span></td>
<td align="left"><span class="math inline">\(\cdots\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{1k}\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{1}\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"><span class="math inline">\(\ddots\)</span></td>
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(r\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{r1}\)</span></td>
<td align="left"><span class="math inline">\(\cdots\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{rk}\)</span></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{r}\)</span></td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{\cdot 1}\)</span></td>
<td align="left"></td>
<td align="left"><span class="math inline">\(\mathrm{n}_{\cdot k}\)</span></td>
<td align="left"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table></div>
<p>y queremos contrastar la hipótesis</p>
<p><span class="math display">\[
\begin{aligned}
p_{11}&amp;=p_{21}=\cdots=p_{r1},\\
p_{12}&amp;=p_{22}=\cdots=p_{r2},\\
&amp;\ \vdots\\
p_{1k}&amp;=p_{2k}=\cdots=p_{rk}.
\end{aligned}
\]</span></p>
<p>De forma análoga al apartado anterior puede establecerse que el estadístico</p>
<p><span class="math display">\[
D^{2}=\sum_{i=1}^{k}\sum_{j=1}^{r}
\frac{\left(n_{ij}-n_{i}\frac{n_{\cdot j}}{n}\right)^{2}}
{n_{i}\frac{n_{\cdot j}}{n}}
\]</span></p>
<p>verifica</p>
<p><span class="math display">\[
D^{2}\xrightarrow[n\to\infty]{\mathcal{L}} \chi^{2}_{(r-1)(k-1)},
\]</span></p>
<p>de modo que la hipótesis nula se rechazará siempre que</p>
<p><span class="math display">\[
D^{2}\ge \chi^{2}_{(k-1)(r-1),\,1-\alpha}.
\]</span></p>
<div id="ejemplo-6-homogeneidad-en-los-grupos-sanguíneos" class="section level3" number="13.4.1">
<h3>
<span class="header-section-number">13.4.1</span> Ejemplo 6: Homogeneidad en los grupos sanguíneos<a class="anchor" aria-label="anchor" href="#ejemplo-6-homogeneidad-en-los-grupos-sangu%C3%ADneos"><i class="fas fa-link"></i></a>
</h3>
<p>En un estudio antropológico se analiza la distribución de los grupos sanguíneos <span class="math inline">\(O,A,B,AB\)</span> entre tres razas humanas. La siguiente tabla contiene las frecuencias observadas y esperadas, así como el análisis realizado con el programa SPSS, donde se observa que no se puede rechazar la hipótesis nula de que la probabilidad de cada grupo sanguíneo es la misma en todas las razas.</p>
<p><strong>Tabla de contingencia Raza × Grupo sanguíneo</strong></p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="left"></th>
<th align="left"></th>
<th align="left">Grupo sanguíneo</th>
<th align="left"></th>
<th align="left"></th>
<th align="left"></th>
<th align="left">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">O</td>
<td align="left">A</td>
<td align="left">B</td>
<td align="left">AB</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Raza</td>
<td align="left">Caucásicos</td>
<td align="left">Recuento</td>
<td align="left">32</td>
<td align="left">11</td>
<td align="left">7</td>
<td align="left">2</td>
<td align="left">52</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left">Frecuencia esperada</td>
<td align="left">29.0</td>
<td align="left">8.8</td>
<td align="left">9.4</td>
<td align="left">4.8</td>
<td align="left">52.0</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left">% de grupo sanguíneo</td>
<td align="left">31.4%</td>
<td align="left">35.5%</td>
<td align="left">21.2%</td>
<td align="left">11.8%</td>
<td align="left">28.4%</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Pigmeos</td>
<td align="left">Recuento</td>
<td align="left">47</td>
<td align="left">13</td>
<td align="left">17</td>
<td align="left">9</td>
<td align="left">86</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left">Frecuencia esperada</td>
<td align="left">47.9</td>
<td align="left">14.6</td>
<td align="left">15.5</td>
<td align="left">8.0</td>
<td align="left">86.0</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left">% de grupo sanguíneo</td>
<td align="left">46.1%</td>
<td align="left">41.9%</td>
<td align="left">51.5%</td>
<td align="left">52.9%</td>
<td align="left">47.0%</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Esquimales</td>
<td align="left">Recuento</td>
<td align="left">23</td>
<td align="left">7</td>
<td align="left">9</td>
<td align="left">6</td>
<td align="left">45</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left">Frecuencia esperada</td>
<td align="left">25.1</td>
<td align="left">7.6</td>
<td align="left">8.1</td>
<td align="left">4.2</td>
<td align="left">45.0</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left">% de grupo sanguíneo</td>
<td align="left">22.5%</td>
<td align="left">22.6%</td>
<td align="left">27.3%</td>
<td align="left">35.3%</td>
<td align="left">24.6%</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left"></td>
<td align="left">Recuento</td>
<td align="left">102</td>
<td align="left">31</td>
<td align="left">33</td>
<td align="left">17</td>
<td align="left">183</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left">Frecuencia esperada</td>
<td align="left">102.0</td>
<td align="left">31.0</td>
<td align="left">33.0</td>
<td align="left">17.0</td>
<td align="left">183.0</td>
</tr>
</tbody>
</table></div>
<p>A partir de esta información queremos contrastar si la distribución de los grupos sanguíneos es la misma en las tres razas consideradas. Formalmente, planteamos el contraste de homogeneidad:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: p_{1j}=p_{2j}=p_{3j}, \quad j=1,\ldots,4, \\
H_1 &amp;: \text{no todas las probabilidades anteriores son iguales}.
\end{aligned}
\]</span></p>
<p>Bajo la hipótesis nula, la frecuencia esperada en la celda correspondiente a la raza <span class="math inline">\(i\)</span> y al grupo sanguíneo <span class="math inline">\(j\)</span> viene dada por</p>
<p><span class="math display">\[
E_{ij}=\frac{n_{i\cdot}\,n_{\cdot j}}{n},
\]</span></p>
<p>donde <span class="math inline">\(n_{i\cdot}\)</span> es el total de individuos de la raza <span class="math inline">\(i\)</span>, <span class="math inline">\(n_{\cdot j}\)</span> el total del grupo sanguíneo <span class="math inline">\(j\)</span> y <span class="math inline">\(n\)</span> el tamaño muestral total. Estas frecuencias esperadas son las que figuran en la tabla anterior.</p>
<p>El estadístico de contraste es el estadístico de Pearson</p>
<p><span class="math display">\[
D^{2}
=
\sum_{i=1}^{3}\sum_{j=1}^{4}
\frac{(n_{ij}-E_{ij})^{2}}{E_{ij}},
\]</span></p>
<p>que mide la discrepancia global entre las frecuencias observadas y las esperadas bajo la hipótesis de homogeneidad.</p>
<p>En este caso, la tabla tiene <span class="math inline">\(r=3\)</span> filas y <span class="math inline">\(k=4\)</span> columnas, por lo que, bajo <span class="math inline">\(H_{0}\)</span>, el estadístico <span class="math inline">\(D^{2}\)</span> sigue asintóticamente una distribución ji-cuadrado con</p>
<p><span class="math display">\[
(r-1)(k-1)=(3-1)(4-1)=6
\]</span></p>
<p>grados de libertad.</p>
<p>El análisis realizado muestra que el valor observado del estadístico es inferior al valor crítico de una distribución <span class="math inline">\(\chi^{2}_{6}\)</span> al nivel de significación <span class="math inline">\(\alpha=0.05\)</span>, cuyo percentil 0.95 es <span class="math inline">\(\chi^{2}_{6,0.95}=12.59\)</span>. De forma equivalente, el <span class="math inline">\(p\)</span>-valor asociado al contraste es suficientemente grande.</p>
<p>Por tanto, <strong>no se rechaza la hipótesis nula de homogeneidad</strong>, y los datos son compatibles con la hipótesis de que la probabilidad de pertenecer a cada grupo sanguíneo es la misma en las tres razas consideradas.</p>
</div>
</div>
<div id="ejemplos-resueltos-en-r" class="section level2" number="13.5">
<h2>
<span class="header-section-number">13.5</span> Ejemplos resueltos en R<a class="anchor" aria-label="anchor" href="#ejemplos-resueltos-en-r"><i class="fas fa-link"></i></a>
</h2>
<p>La primera versión de este documento se creó en un momento en que R no era la herramienta universal de los estadísticos por lo que los ejemplos estan resueltos para ser calculados manualmente. En el caso de las pruebas chi-cuadrado esto resulta particularmente interesante por lo que se ha mantenido dicha resolución y se incluyen a continuación la resolución de cada ejercicio con R.</p>
<div id="ejemplo-1-bondad-de-ajuste-1" class="section level3" number="13.5.1">
<h3>
<span class="header-section-number">13.5.1</span> Ejemplo 1: Bondad de ajuste<a class="anchor" aria-label="anchor" href="#ejemplo-1-bondad-de-ajuste-1"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Datos (200 días).</strong> Se contrasta <span class="math inline">\(H_0: X \sim \text{Poisson}(\lambda=2)\)</span>.</p>
<div class="sourceCode" id="cb92"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">200</span></span>
<span><span class="va">obs_raw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`0`<span class="op">=</span><span class="fl">22</span>, `1`<span class="op">=</span><span class="fl">53</span>, `2`<span class="op">=</span><span class="fl">58</span>, `3`<span class="op">=</span><span class="fl">39</span>, `4`<span class="op">=</span><span class="fl">20</span>, `5`<span class="op">=</span><span class="fl">5</span>, `6`<span class="op">=</span><span class="fl">2</span>, `7`<span class="op">=</span><span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Agrupamos en categoría "&gt;=5" para evitar esperadas pequeñas</span></span>
<span><span class="va">obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`0`<span class="op">=</span><span class="va">obs_raw</span><span class="op">[</span><span class="st">"0"</span><span class="op">]</span>,</span>
<span>         `1`<span class="op">=</span><span class="va">obs_raw</span><span class="op">[</span><span class="st">"1"</span><span class="op">]</span>,</span>
<span>         `2`<span class="op">=</span><span class="va">obs_raw</span><span class="op">[</span><span class="st">"2"</span><span class="op">]</span>,</span>
<span>         `3`<span class="op">=</span><span class="va">obs_raw</span><span class="op">[</span><span class="st">"3"</span><span class="op">]</span>,</span>
<span>         `4`<span class="op">=</span><span class="va">obs_raw</span><span class="op">[</span><span class="st">"4"</span><span class="op">]</span>,</span>
<span>         `&gt;=5`<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">obs_raw</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"5"</span>,<span class="st">"6"</span>,<span class="st">"7"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">obs</span></span></code></pre></div>
<pre><code>## 0.0 1.1 2.2 3.3 4.4 &gt;=5 
##  22  53  58  39  20   8</code></pre>
<div class="sourceCode" id="cb94"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 200</code></pre>
<div class="sourceCode" id="cb96"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lambda</span> <span class="op">&lt;-</span> <span class="fl">2</span></span>
<span></span>
<span><span class="co"># Probabilidades bajo Poisson(2): 0..4 y &gt;=5</span></span>
<span><span class="va">p0_4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">dpois</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">4</span>, lambda <span class="op">=</span> <span class="va">lambda</span><span class="op">)</span></span>
<span><span class="va">p_ge5</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Poisson.html">ppois</a></span><span class="op">(</span><span class="fl">4</span>, lambda <span class="op">=</span> <span class="va">lambda</span><span class="op">)</span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p0_4</span>, <span class="va">p_ge5</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Comprobación: suman 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Test chi-cuadrado (probabilidades completamente especificadas)</span></span>
<span><span class="va">test1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">obs</span>, p <span class="op">=</span> <span class="va">p</span>, rescale.p <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">test1</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  obs
## X-squared = 2.3031, df = 5, p-value = 0.8058</code></pre>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">expected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">test1</span><span class="op">$</span><span class="va">expected</span><span class="op">)</span></span>
<span><span class="va">stat_contrib</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">obs</span> <span class="op">-</span> <span class="va">expected</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">expected</span></span>
<span></span>
<span><span class="va">res1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Categoria <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>,</span>
<span>  Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>,</span>
<span>  p0 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span>,</span>
<span>  Esperado <span class="op">=</span> <span class="va">expected</span>,</span>
<span>  Contribucion <span class="op">=</span> <span class="va">stat_contrib</span></span>
<span><span class="op">)</span></span>
<span><span class="va">res1</span></span></code></pre></div>
<pre><code>##     Categoria Observado         p0 Esperado Contribucion
## 0.0       0.0        22 0.13533528 27.06706   0.94857241
## 1.1       1.1        53 0.27067057 54.13411   0.02375975
## 2.2       2.2        58 0.27067057 54.13411   0.27607509
## 3.3       3.3        39 0.18044704 36.08941   0.23473759
## 4.4       4.4        20 0.09022352 18.04470   0.21187273
## &gt;=5       &gt;=5         8 0.05265302 10.53060   0.60812791</code></pre>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">res1</span><span class="op">$</span><span class="va">Contribucion</span><span class="op">)</span>  <span class="co"># Debe coincidir con el estadístico</span></span></code></pre></div>
<pre><code>## [1] 2.303145</code></pre>
<div class="sourceCode" id="cb104"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">op</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mar<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">4</span>,<span class="fl">2</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">bp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>, Esperado <span class="op">=</span> <span class="va">expected</span><span class="op">)</span>,</span>
<span>              beside <span class="op">=</span> <span class="cn">TRUE</span>, las <span class="op">=</span> <span class="fl">2</span>, ylab <span class="op">=</span> <span class="st">"Frecuencia"</span>,</span>
<span>              main <span class="op">=</span> <span class="st">"Ejemplo 1: Observado vs Esperado (Poisson(2))"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Observado"</span>,<span class="st">"Esperado"</span><span class="op">)</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej1-plot-1.png" alt="" width="672"></div>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="va">op</span><span class="op">)</span></span></code></pre></div>
<hr>
</div>
<div id="ejemplo-2-ajuste-de-modelo-genético-1" class="section level3" number="13.5.2">
<h3>
<span class="header-section-number">13.5.2</span> Ejemplo 2: Ajuste de modelo genético<a class="anchor" aria-label="anchor" href="#ejemplo-2-ajuste-de-modelo-gen%C3%A9tico-1"><i class="fas fa-link"></i></a>
</h3>
<p>Modelo: proporciones <span class="math inline">\(1:2:1\)</span> (multinomial con <span class="math inline">\(p=(0.25,0.5,0.25)\)</span>).</p>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>Blanca <span class="op">=</span> <span class="fl">112</span>, Rosa <span class="op">=</span> <span class="fl">242</span>, Roja <span class="op">=</span> <span class="fl">112</span><span class="op">)</span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.25</span><span class="op">)</span></span>
<span></span>
<span><span class="va">test2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">obs</span>, p <span class="op">=</span> <span class="va">p</span>, rescale.p <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">test2</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  obs
## X-squared = 0.69528, df = 2, p-value = 0.7064</code></pre>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">expected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">test2</span><span class="op">$</span><span class="va">expected</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  Categoria <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>,</span>
<span>  Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>,</span>
<span>  Esperado  <span class="op">=</span> <span class="va">expected</span>,</span>
<span>  Contribucion <span class="op">=</span> <span class="op">(</span><span class="va">obs</span><span class="op">-</span><span class="va">expected</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">/</span><span class="va">expected</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>##        Categoria Observado Esperado Contribucion
## Blanca    Blanca       112    116.5    0.1738197
## Rosa        Rosa       242    233.0    0.3476395
## Roja        Roja       112    116.5    0.1738197</code></pre>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>, Esperado <span class="op">=</span> <span class="va">expected</span><span class="op">)</span>,</span>
<span>        beside <span class="op">=</span> <span class="cn">TRUE</span>, las <span class="op">=</span> <span class="fl">2</span>, ylab <span class="op">=</span> <span class="st">"Frecuencia"</span>,</span>
<span>        main <span class="op">=</span> <span class="st">"Ejemplo 2: Observado vs Esperado (1:2:1)"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Observado"</span>,<span class="st">"Esperado"</span><span class="op">)</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej2-tabla-plot-1.png" alt="" width="672"></div>
<hr>
</div>
<div id="ejemplo-3-ajuste-de-modelo-genético-con-probabilidades-desconocidas-1" class="section level3" number="13.5.3">
<h3>
<span class="header-section-number">13.5.3</span> Ejemplo 3: Ajuste de modelo genético con probabilidades desconocidas<a class="anchor" aria-label="anchor" href="#ejemplo-3-ajuste-de-modelo-gen%C3%A9tico-con-probabilidades-desconocidas-1"><i class="fas fa-link"></i></a>
</h3>
<p>Se contrasta el ajuste a un <strong>modelo Hardy–Weinberg</strong> para alelos <span class="math inline">\(M/N\)</span>:</p>
<p><span class="math display">\[p_1(p)=p^2,\quad p_2(p)=2p(1-p),\quad p_3(p)=(1-p)^2,\]</span>
estimando <span class="math inline">\(p\)</span> por máxima verosimilitud.</p>
<p>Datos:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>Grupo</th>
<th align="right">M</th>
<th align="right">M-N</th>
<th align="right">N</th>
</tr></thead>
<tbody><tr class="odd">
<td>Individuos</td>
<td align="right">1787</td>
<td align="right">3039</td>
<td align="right">1303</td>
</tr></tbody>
</table></div>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fl">1787</span></span>
<span><span class="va">n2</span> <span class="op">&lt;-</span> <span class="fl">3039</span></span>
<span><span class="va">n3</span> <span class="op">&lt;-</span> <span class="fl">1303</span></span>
<span><span class="va">n</span>  <span class="op">&lt;-</span> <span class="va">n1</span> <span class="op">+</span> <span class="va">n2</span> <span class="op">+</span> <span class="va">n3</span></span>
<span></span>
<span><span class="va">p_hat</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">2</span><span class="op">*</span><span class="va">n1</span> <span class="op">+</span> <span class="va">n2</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">2</span><span class="op">*</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">p_hat</span></span></code></pre></div>
<pre><code>## [1] 0.5394844</code></pre>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>M <span class="op">=</span> <span class="va">p_hat</span><span class="op">^</span><span class="fl">2</span>,</span>
<span>             `M-N` <span class="op">=</span> <span class="fl">2</span><span class="op">*</span><span class="va">p_hat</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">p_hat</span><span class="op">)</span>,</span>
<span>             N <span class="op">=</span> <span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">p_hat</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">expected</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">*</span> <span class="va">p_model</span></span>
<span><span class="va">obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>M <span class="op">=</span> <span class="va">n1</span>, `M-N` <span class="op">=</span> <span class="va">n2</span>, N <span class="op">=</span> <span class="va">n3</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Estadístico de Pearson</span></span>
<span><span class="va">D2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">obs</span> <span class="op">-</span> <span class="va">expected</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">expected</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Grados de libertad ajustados: k - 1 - m = 3 - 1 - 1 = 1</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span><span class="va">p_value</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="va">D2</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  p_hat <span class="op">=</span> <span class="va">p_hat</span>,</span>
<span>  expected <span class="op">=</span> <span class="va">expected</span>,</span>
<span>  D2 <span class="op">=</span> <span class="va">D2</span>,</span>
<span>  df <span class="op">=</span> <span class="va">df</span>,</span>
<span>  p_value <span class="op">=</span> <span class="va">p_value</span></span>
<span><span class="op">)</span></span></code></pre></div>
<pre><code>## $p_hat
## [1] 0.5394844
## 
## $expected
##        M      M-N        N 
## 1783.805 3045.390 1299.805 
## 
## $D2
## [1] 0.02698008
## 
## $df
## [1] 1
## 
## $p_value
## [1] 0.8695295</code></pre>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>, Esperado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">expected</span><span class="op">)</span><span class="op">)</span>,</span>
<span>        beside <span class="op">=</span> <span class="cn">TRUE</span>, las <span class="op">=</span> <span class="fl">2</span>, ylab <span class="op">=</span> <span class="st">"Frecuencia"</span>,</span>
<span>        main <span class="op">=</span> <span class="st">"Ejemplo 3: Observado vs Esperado (modelo con p estimado)"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Observado"</span>,<span class="st">"Esperado"</span><span class="op">)</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej3-plot-1.png" alt="" width="672"></div>
<hr>
</div>
<div id="ejemplo-4-ajuste-a-una-distribución-normal-1" class="section level3" number="13.5.4">
<h3>
<span class="header-section-number">13.5.4</span> Ejemplo 4: Ajuste a una distribución normal<a class="anchor" aria-label="anchor" href="#ejemplo-4-ajuste-a-una-distribuci%C3%B3n-normal-1"><i class="fas fa-link"></i></a>
</h3>
<p>Se dispone de 211 puntuaciones tabuladas:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="9%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
<col width="12%">
</colgroup>
<thead><tr class="header">
<th>Intervalo</th>
<th align="right"><span class="math inline">\((\leq 55]\)</span></th>
<th align="right"><span class="math inline">\((55-60]\)</span></th>
<th align="right"><span class="math inline">\((60-65]\)</span></th>
<th align="right"><span class="math inline">\((65-70]\)</span></th>
<th align="right"><span class="math inline">\((70-75]\)</span></th>
<th align="right"><span class="math inline">\((75-80]\)</span></th>
<th align="right"><span class="math inline">\((80-85]\)</span></th>
</tr></thead>
<tbody><tr class="odd">
<td>Frecuencia</td>
<td align="right">4</td>
<td align="right">17</td>
<td align="right">45</td>
<td align="right">67</td>
<td align="right">53</td>
<td align="right">15</td>
<td align="right">10</td>
</tr></tbody>
</table></div>
<p>Queremos contrastar <span class="math inline">\(H_0: X \sim N(\mu,\sigma)\)</span>, con <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> <strong>desconocidos</strong> (se estiman).</p>
<blockquote>
<p>Importante: como se estiman 2 parámetros, el contraste usa <strong><span class="math inline">\(k-1-m\)</span></strong> grados de libertad tras posibles fusiones de clases.</p>
</blockquote>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">obs_raw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`&lt;=55`<span class="op">=</span><span class="fl">4</span>, `55-60`<span class="op">=</span><span class="fl">17</span>, `60-65`<span class="op">=</span><span class="fl">45</span>, `65-70`<span class="op">=</span><span class="fl">67</span>, `70-75`<span class="op">=</span><span class="fl">53</span>, `75-80`<span class="op">=</span><span class="fl">15</span>, `80-85`<span class="op">=</span><span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">obs_raw</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">mu_hat</span> <span class="op">&lt;-</span> <span class="fl">68.52</span></span>
<span><span class="va">sigma_hat</span> <span class="op">&lt;-</span> <span class="fl">6.44</span></span>
<span><span class="va">mu_hat</span>; <span class="va">sigma_hat</span></span></code></pre></div>
<pre><code>## [1] 68.52</code></pre>
<pre><code>## [1] 6.44</code></pre>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Intervalos: (-Inf,55], (55,60], ..., (80,Inf)</span></span>
<span><span class="va">breaks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="cn">Inf</span>, <span class="fl">55</span>, <span class="fl">60</span>, <span class="fl">65</span>, <span class="fl">70</span>, <span class="fl">75</span>, <span class="fl">80</span>, <span class="cn">Inf</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">breaks</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">a</span> <span class="op">&lt;-</span> <span class="va">breaks</span><span class="op">[</span><span class="va">i</span><span class="op">]</span>; <span class="va">b</span> <span class="op">&lt;-</span> <span class="va">breaks</span><span class="op">[</span><span class="va">i</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span></span>
<span>  <span class="va">p</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">b</span>, mean <span class="op">=</span> <span class="va">mu_hat</span>, sd <span class="op">=</span> <span class="va">sigma_hat</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">a</span>, mean <span class="op">=</span> <span class="va">mu_hat</span>, sd <span class="op">=</span> <span class="va">sigma_hat</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`&lt;=55`<span class="op">=</span><span class="fl">1</span>, `55-60`<span class="op">=</span><span class="fl">1</span>, `60-65`<span class="op">=</span><span class="fl">1</span>, `65-70`<span class="op">=</span><span class="fl">1</span>, `70-75`<span class="op">=</span><span class="fl">1</span>, `75-80`<span class="op">=</span><span class="fl">1</span>, `&gt;=80`<span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">p</span></span></code></pre></div>
<pre><code>##       &lt;=55      55-60      60-65      65-70      70-75      75-80       &gt;=80 
## 0.01789176 0.07502903 0.19941155 0.29854938 0.25196129 0.11983199 0.03732501</code></pre>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">p</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb123"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">expected_raw</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">*</span> <span class="va">p</span></span>
<span></span>
<span><span class="co"># Fusionamos las dos primeras clases si alguna esperada &lt; 5 (en el texto se fusionan)</span></span>
<span><span class="va">obs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`&lt;=60` <span class="op">=</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"&lt;=55"</span><span class="op">]</span> <span class="op">+</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"55-60"</span><span class="op">]</span>,</span>
<span>         `60-65` <span class="op">=</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"60-65"</span><span class="op">]</span>,</span>
<span>         `65-70` <span class="op">=</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"65-70"</span><span class="op">]</span>,</span>
<span>         `70-75` <span class="op">=</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"70-75"</span><span class="op">]</span>,</span>
<span>         `75-80` <span class="op">=</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"75-80"</span><span class="op">]</span>,</span>
<span>         `&gt;=80`  <span class="op">=</span> <span class="va">obs_raw</span><span class="op">[</span><span class="st">"80-85"</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="va">expected</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>`&lt;=60` <span class="op">=</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>              `60-65` <span class="op">=</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>,</span>
<span>              `65-70` <span class="op">=</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span>,</span>
<span>              `70-75` <span class="op">=</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">5</span><span class="op">]</span>,</span>
<span>              `75-80` <span class="op">=</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">6</span><span class="op">]</span>,</span>
<span>              `&gt;=80`  <span class="op">=</span> <span class="va">expected_raw</span><span class="op">[</span><span class="fl">7</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Categoria <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>,</span>
<span>           Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>,</span>
<span>           Esperado  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">expected</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##     Categoria Observado  Esperado
## 1   &lt;=60.&lt;=55        21 19.606286
## 2 60-65.60-65        45 42.075836
## 3 65-70.65-70        67 62.993920
## 4 70-75.70-75        53 53.163831
## 5 75-80.75-80        15 25.284549
## 6  &gt;=80.80-85        10  7.875577</code></pre>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Estadístico de Pearson</span></span>
<span><span class="va">D2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">obs</span> <span class="op">-</span> <span class="va">expected</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">expected</span><span class="op">)</span></span>
<span></span>
<span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>        <span class="co"># número final de clases</span></span>
<span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fl">2</span>                  <span class="co"># mu y sigma estimados</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">k</span> <span class="op">-</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">m</span></span>
<span></span>
<span><span class="va">p_value</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="va">D2</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>D2 <span class="op">=</span> <span class="va">D2</span>, df <span class="op">=</span> <span class="va">df</span>, p_value <span class="op">=</span> <span class="va">p_value</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $D2
## [1] 5.313888
## 
## $df
## [1] 3
## 
## $p_value
## [1] 0.1502038</code></pre>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>Observado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">obs</span><span class="op">)</span>, Esperado <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">expected</span><span class="op">)</span><span class="op">)</span>,</span>
<span>        beside <span class="op">=</span> <span class="cn">TRUE</span>, las <span class="op">=</span> <span class="fl">2</span>, ylab <span class="op">=</span> <span class="st">"Frecuencia"</span>,</span>
<span>        main <span class="op">=</span> <span class="st">"Ejemplo 4: Observado vs Esperado (Normal con parámetros estimados)"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Observado"</span>,<span class="st">"Esperado"</span><span class="op">)</span>, bty <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej4-plot-1.png" alt="" width="672"></div>
</div>
<div id="ejemplo-5-relación-entre-nivel-de-estudios-y-preferencias-1" class="section level3" number="13.5.5">
<h3>
<span class="header-section-number">13.5.5</span> Ejemplo 5: Relación entre nivel de estudios y preferencias<a class="anchor" aria-label="anchor" href="#ejemplo-5-relaci%C3%B3n-entre-nivel-de-estudios-y-preferencias-1"><i class="fas fa-link"></i></a>
</h3>
<p>Tabla (Nivel de estudios × Tipo de vehículo):</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">31</span>,<span class="fl">49</span>,<span class="fl">18</span>,<span class="fl">12</span>,</span>
<span>    <span class="fl">11</span>,<span class="fl">59</span>,<span class="fl">26</span>,<span class="fl">25</span>,</span>
<span>    <span class="fl">12</span>,<span class="fl">51</span>,<span class="fl">31</span>,<span class="fl">36</span><span class="op">)</span>,</span>
<span>  nrow <span class="op">=</span> <span class="fl">3</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Elementales"</span>,<span class="st">"Nivel medio"</span>,<span class="st">"Superiores"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Ninguno"</span>,<span class="st">"Motos"</span>,<span class="st">"C. normal"</span>,<span class="st">"C. potente"</span><span class="op">)</span></span>
<span><span class="va">tab</span></span></code></pre></div>
<pre><code>##             Ninguno Motos C. normal C. potente
## Elementales      31    49        18         12
## Nivel medio      11    59        26         25
## Superiores       12    51        31         36</code></pre>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/addmargins.html">addmargins</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span></span></code></pre></div>
<pre><code>##             Ninguno Motos C. normal C. potente Sum
## Elementales      31    49        18         12 110
## Nivel medio      11    59        26         25 121
## Superiores       12    51        31         36 130
## Sum              54   159        75         73 361</code></pre>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">test5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">tab</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">test5</span></span></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test
## 
## data:  tab
## X-squared = 29.763, df = 6, p-value = 4.361e-05</code></pre>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">test5</span><span class="op">$</span><span class="va">expected</span></span></code></pre></div>
<pre><code>##              Ninguno    Motos C. normal C. potente
## Elementales 16.45429 48.44875  22.85319   22.24377
## Nivel medio 18.09972 53.29363  25.13850   24.46814
## Superiores  19.44598 57.25762  27.00831   26.28809</code></pre>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/mosaicplot.html">mosaicplot</a></span><span class="op">(</span><span class="va">tab</span>, shade <span class="op">=</span> <span class="cn">TRUE</span>, las <span class="op">=</span> <span class="fl">1</span>,</span>
<span>           main <span class="op">=</span> <span class="st">"Ejemplo 5: Mosaicplot (independencia)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej5-plot-1.png" alt="" width="672"></div>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/assocplot.html">assocplot</a></span><span class="op">(</span><span class="va">tab</span>, main <span class="op">=</span> <span class="st">"Ejemplo 5: Assocplot (residuales estandarizados)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej5-plot-2.png" alt="" width="672"></div>
</div>
<div id="ejemplo-6-homogeneidad-en-los-grupos-sanguíneos-1" class="section level3" number="13.5.6">
<h3>
<span class="header-section-number">13.5.6</span> Ejemplo 6: Homogeneidad en los grupos sanguíneos<a class="anchor" aria-label="anchor" href="#ejemplo-6-homogeneidad-en-los-grupos-sangu%C3%ADneos-1"><i class="fas fa-link"></i></a>
</h3>
<p>Tabla (Raza × Grupo sanguíneo):</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">tab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">32</span>,<span class="fl">11</span>,<span class="fl">7</span>,<span class="fl">2</span>,</span>
<span>    <span class="fl">47</span>,<span class="fl">13</span>,<span class="fl">17</span>,<span class="fl">9</span>,</span>
<span>    <span class="fl">23</span>,<span class="fl">7</span>,<span class="fl">9</span>,<span class="fl">6</span><span class="op">)</span>,</span>
<span>  nrow <span class="op">=</span> <span class="fl">3</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Caucásicos"</span>,<span class="st">"Pigmeos"</span>,<span class="st">"Esquimales"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"O"</span>,<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"AB"</span><span class="op">)</span></span>
<span><span class="va">tab</span></span></code></pre></div>
<pre><code>##             O  A  B AB
## Caucásicos 32 11  7  2
## Pigmeos    47 13 17  9
## Esquimales 23  7  9  6</code></pre>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/addmargins.html">addmargins</a></span><span class="op">(</span><span class="va">tab</span><span class="op">)</span></span></code></pre></div>
<pre><code>##              O  A  B AB Sum
## Caucásicos  32 11  7  2  52
## Pigmeos     47 13 17  9  86
## Esquimales  23  7  9  6  45
## Sum        102 31 33 17 183</code></pre>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># El test de homogeneidad se implementa igual que el test de independencia sobre la tabla de recuentos</span></span>
<span><span class="va">test6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">tab</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">test6</span></span></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test
## 
## data:  tab
## X-squared = 4.6911, df = 6, p-value = 0.584</code></pre>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">test6</span><span class="op">$</span><span class="va">expected</span></span></code></pre></div>
<pre><code>##                   O         A         B       AB
## Caucásicos 28.98361  8.808743  9.377049 4.830601
## Pigmeos    47.93443 14.568306 15.508197 7.989071
## Esquimales 25.08197  7.622951  8.114754 4.180328</code></pre>
<div class="sourceCode" id="cb146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/mosaicplot.html">mosaicplot</a></span><span class="op">(</span><span class="va">tab</span>, shade <span class="op">=</span> <span class="cn">TRUE</span>, las <span class="op">=</span> <span class="fl">1</span>,</span>
<span>           main <span class="op">=</span> <span class="st">"Ejemplo 6: Mosaicplot (homogeneidad)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej6-plot-1.png" alt="" width="672"></div>
<div class="sourceCode" id="cb147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/assocplot.html">assocplot</a></span><span class="op">(</span><span class="va">tab</span>, main <span class="op">=</span> <span class="st">"Ejemplo 6: Assocplot (residuales estandarizados)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="FundamentosInferencia-completo_files/figure-html/ej6-plot-2.png" alt="" width="672"></div>

<div style="page-break-after: always;"></div>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="contrastes-con-dos-muestras.html"><span class="header-section-number">12</span> Contrastes con dos muestras</a></div>
<div class="next"><a href="estad%C3%ADstica-no-param%C3%A9trica.html"><span class="header-section-number">14</span> Estadística no paramétrica</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="En esta página"><h2>En esta página</h2>
<ul class="nav navbar-nav">
<li><a class="nav-link" href="#las-pruebas-chi-cuadrado"><span class="header-section-number">13</span> Las pruebas “Chi-cuadrado”</a></li>
<li><a class="nav-link" href="#introducci%C3%B3n-8"><span class="header-section-number">13.1</span> Introducción</a></li>
<li>
<a class="nav-link" href="#pruebas-chi2-de-bondad-de-ajuste"><span class="header-section-number">13.2</span> Pruebas \(\chi^2\) de bondad de ajuste</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#hip%C3%B3tesis-simples"><span class="header-section-number">13.2.1</span> Hipótesis simples</a></li>
<li><a class="nav-link" href="#estad%C3%ADstico-de-pearson"><span class="header-section-number">13.2.2</span> Estadístico de Pearson</a></li>
<li><a class="nav-link" href="#observaciones-pr%C3%A1cticas"><span class="header-section-number">13.2.3</span> Observaciones prácticas</a></li>
<li><a class="nav-link" href="#ejemplo-1-bondad-de-ajuste"><span class="header-section-number">13.2.4</span> Ejemplo 1: Bondad de ajuste</a></li>
<li><a class="nav-link" href="#ejemplo-2-ajuste-de-modelo-gen%C3%A9tico"><span class="header-section-number">13.2.5</span> Ejemplo 2: Ajuste de modelo genético</a></li>
<li><a class="nav-link" href="#hip%C3%B3tesis-compuestas"><span class="header-section-number">13.2.6</span> Hipótesis compuestas</a></li>
<li><a class="nav-link" href="#ejemplo-3-ajuste-de-modelo-gen%C3%A9tico-con-probabilidades-desconocidas"><span class="header-section-number">13.2.7</span> Ejemplo 3: Ajuste de modelo genético con probabilidades desconocidas</a></li>
<li><a class="nav-link" href="#ejemplo-4-ajuste-a-una-distribuci%C3%B3n-normal"><span class="header-section-number">13.2.8</span> Ejemplo 4: Ajuste a una distribución normal</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#pruebas-de-independencia-en-tablas-de-contingencia"><span class="header-section-number">13.3</span> Pruebas de independencia en tablas de contingencia</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplo-5-relaci%C3%B3n-entre-nivel-de-estudios-y-preferencias"><span class="header-section-number">13.3.1</span> Ejemplo 5: Relación entre nivel de estudios y preferencias</a></li></ul>
</li>
<li>
<a class="nav-link" href="#pruebas-de-homogeneidad"><span class="header-section-number">13.4</span> Pruebas de homogeneidad</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#ejemplo-6-homogeneidad-en-los-grupos-sangu%C3%ADneos"><span class="header-section-number">13.4.1</span> Ejemplo 6: Homogeneidad en los grupos sanguíneos</a></li></ul>
</li>
<li>
<a class="nav-link" href="#ejemplos-resueltos-en-r"><span class="header-section-number">13.5</span> Ejemplos resueltos en R</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#ejemplo-1-bondad-de-ajuste-1"><span class="header-section-number">13.5.1</span> Ejemplo 1: Bondad de ajuste</a></li>
<li><a class="nav-link" href="#ejemplo-2-ajuste-de-modelo-gen%C3%A9tico-1"><span class="header-section-number">13.5.2</span> Ejemplo 2: Ajuste de modelo genético</a></li>
<li><a class="nav-link" href="#ejemplo-3-ajuste-de-modelo-gen%C3%A9tico-con-probabilidades-desconocidas-1"><span class="header-section-number">13.5.3</span> Ejemplo 3: Ajuste de modelo genético con probabilidades desconocidas</a></li>
<li><a class="nav-link" href="#ejemplo-4-ajuste-a-una-distribuci%C3%B3n-normal-1"><span class="header-section-number">13.5.4</span> Ejemplo 4: Ajuste a una distribución normal</a></li>
<li><a class="nav-link" href="#ejemplo-5-relaci%C3%B3n-entre-nivel-de-estudios-y-preferencias-1"><span class="header-section-number">13.5.5</span> Ejemplo 5: Relación entre nivel de estudios y preferencias</a></li>
<li><a class="nav-link" href="#ejemplo-6-homogeneidad-en-los-grupos-sangu%C3%ADneos-1"><span class="header-section-number">13.5.6</span> Ejemplo 6: Homogeneidad en los grupos sanguíneos</a></li>
</ul>
</li>
</ul>
<div class="book-extra"><ul class="list-unstyled"></ul></div></nav>
</div>
</div>
</div>
<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">
<div class="col-12 col-md-6 mt-3"><p>"<strong>Fundamentos de Inferencia Estadistica</strong>" was written by Alex Sanchez Pla y Santiago Pérez Hoyos. It was last built on 2026-09-13.</p></div>
<div class="col-12 col-md-6 mt-3"><p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p></div>
</div></div></footer><script>(function(){var script=document.createElement("script");script.type="text/javascript";var src="true";if(src===""||src==="true")src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";if(location.protocol!=="file:")if(/^https?:/.test(src))src=src.replace(/^https?:/,'');script.src=src;document.getElementsByTagName("head")[0].appendChild(script);})();</script><script type="text/x-mathjax-config">const popovers=document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');for(let popover of popovers){const div=document.createElement('div');div.setAttribute('style','position:absolute;top:0,left:0;width:0,height:0,overflow:hidden;visibility:hidden;');div.innerHTML=popover.getAttribute('data-content');var has_math=div.querySelector("span.math");if(has_math){document.body.appendChild(div);MathJax.Hub.Queue(["Typeset",MathJax.Hub,div]);MathJax.Hub.Queue(function(){popover.setAttribute('data-content',div.innerHTML);document.body.removeChild(div)})}}</script>
</body>
</html>
